### ISSUE TITLE
initialSelectedIndex not work

### ISSUE THREAD

**Issue by iman2420** [sosog/react-native-dynamically-selected-picker#2]
why `initialSelectedIndex `not work ?

     `<DynamicallySelectedPicker
                    items={initYearsArray()}
                    width={width / 3}
                    height={height}
                    transparentItemRows={1}
                    onScroll={(selected) => setSelectedYear(selected.index)}
                    initialSelectedIndex={selectedDay}
                />`

**Comment by sosog** [comment]
> why `initialSelectedIndex `not work ?
It was a bug, because of the first time I worked on FlatList with different property, so i checked IOS and ANDROID and it is working, now, please add your response to close this issue
[5b8995a3ef800e2ebb6100388f6327b81ac0f865](5b8995a3ef800e2ebb6100388f6327b81ac0f865)

**Comment by sosog** [comment]
> why `initialSelectedIndex `not work ?
> 
> ```
>  `<DynamicallySelectedPicker
>                 items={initYearsArray()}
>                 width={width / 3}
>                 height={height}
>                 transparentItemRows={1}
>                 onScroll={(selected) => setSelectedYear(selected.index)}
>                 initialSelectedIndex={selectedDay}
>             />`
> ```
It was a bug, because of the first time I worked on FlatList with different property, so I checked IOS and ANDROID and it is working, now, please add your response to close this issue
https://github.com/sosog/react-native-dynamically-selected-picker/commit/5b8995a3ef800e2ebb6100388f6327b81ac0f865

**Comment by iman2420** [comment]
I did not test this on ANDROID and IOS. I tested on the **WEB** that it did not work

**Comment by sosog** [comment]
> I did not test this on ANDROID and IOS. I tested on the **WEB** that it did not work

Can you please update your local version to 2.0.1  and check it again?
