### ISSUE TITLE
Feature Request：Highlight the selected item

### ISSUE THREAD

**Issue by jadentangsjfood** [sosog/react-native-dynamically-selected-picker#37]
Thank you for developing this library, which has helped me a lot, I found in use that if you can highlight the selected item, and support custom highlighted color values, it is even more perfect.
Thank you again. This question is machine translation, please forgive any inaccuracies

**Comment by sosog** [comment]
Hi @jadentangsjfood , unfortunately, I have no time for it right now, but please, feel free to contribute
